### ISSUE TITLE
Add simultaneous cursor example to https://yorkie.dev

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-team.github.io#109]
**Description**:

We have developed a simultaneous cursor(multi-cursor) example for https://yorkie.dev and examples.

- PR: https://github.com/yorkie-team/yorkie-js-sdk/pull/590
- Design: https://www.figma.com/proto/IBIiGml3fbfxgkSr14fSgy/Yorkie-(Sharing)?type=design&node-id=4552-184611&t=iAmanTZJDoJw3s5l-0&scaling=scale-down&page-id=4537%3A182659&starting-point-node-id=4552%3A184611&show-proto-sidebar=1

However, the example is not ready to display on the homepage.

Let's add the example to https://yorkie.dev/examples and https://yorkie.dev.
- Related to https://github.com/yorkie-team/yorkie-team.github.io/issues/11 and https://github.com/yorkie-team/yorkie-team.github.io/issues/12

**Why**:

**Comment by banma1234** [comment]
`fileInfo.ts` is already exists, is anyone working on this issue?

can i try this if there's no one?

**Comment by hackerwins** [comment]
@banma1234 Of course. Please let me know, if you have any questions.

**Comment by hackerwins** [comment]
@banma1234 Thanks for your contribution. You can find the example by visiting the following page: [Simultaneous Cursors on yorkie.dev](https://yorkie.dev/yorkie-js-sdk/examples/simultaneous-cursors/).

To integrate this example into https://yorkie.dev, please refer to the following Pull Request (PR) for guidance on how to do so: [Adding Example Page](https://github.com/yorkie-team/yorkie-team.github.io/pull/106/files#diff-8b42af19eb0b9d9ad9918759b7adee66b580c3d179955606b34fa15a65bf8c84)

The page that needs to be modified: [Multi-Cursor](https://github.com/yorkie-team/yorkie-team.github.io/blob/main/pages/examples/multi-cursor.tsx)
