### ISSUE TITLE
Incorrect button display in mobile version when logged in

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/yorkie-team.github.io#146]
**What happened**:
In the mobile version of the application, there is an issue with the button display. When a user is logged in, the "Sign In" button is displayed instead of the expected "Dashboard" button.

**What you expected to happen**:
When a user is logged in, the "Dashboard" button should be displayed, and when a user is not logged in, the "Sign In" button should be displayed.

**How to reproduce it (as minimally and precisely as possible)**:
1. When user is not signed in -> Dashboard button is displayed.
    <img width="375" alt="image" src="https://github.com/user-attachments/assets/1c16b4d0-0dd4-44de-8310-d432fdebf075">
2. When user is signed in -> Sign In button is displayed.
    <img width="375" alt="image" src="https://github.com/user-attachments/assets/49f9ed43-486e-432c-bf8d-d64fff8619e7">

**Anything else we need to know?**:

**Environment**:
- Operating system: ALL
- Browser and version: ALL

**Comment by KimKyuHoi** [comment]
Could I give it a try?
