### ISSUE TITLE
I want to know  import pattern to use yorkie-js-sdk

### ISSUE THREAD

**Issue by easylogic** [yorkie-team/yorkie-team.github.io#52]
**Description**:

I want to know  import pattern to use yorkie-js-sdk.

There is no separate text for the syntax below in the manual.

```js
import yorkie from "yorkie-js-sdk"
```

**Comment by hackerwins** [comment]
Thank you for reporting. It would be nice to explain it after npm install.

https://yorkie.dev/docs/getting-started/with-js-sdk#installation

Even in the case of `<script>`, it may be necessary to explain that `yorkie` is created globally.
