### ISSUE TITLE
Change Pagination Behavior to Move Along with User

### ISSUE THREAD

**Issue by krapie** [yorkie-team/yorkie-team.github.io#75]
**Description**:

Change pagination indicator's behavior to move along with user scrolling down/up page.

Currently, pagination indicator is always in the top of the page. It will be better to make pagination indicator move as user scroll down/up the pages.

![Screenshot 2023-05-02 at 4 53 33 PM](https://user-images.githubusercontent.com/70474071/235610827-b083b18f-2b2a-4388-a86f-a49b14d5de5c.png)

Example: [Terraform Tutorial: Provision an EKS Cluster (AWS)](https://developer.hashicorp.com/terraform/tutorials/kubernetes/eks)

![Screenshot 2023-05-02 at 4 57 41 PM](https://user-images.githubusercontent.com/70474071/235611270-64447311-fa2c-49cd-b10b-7378e851a15d.png)

**Why**:

It is hard for user to navigate to specific section in the middle of the page while pagination indicator is not following user's scrolled page position.

**Comment by DongjaJ** [comment]
I'm interested in this issue. Can I try this?

**Comment by krapie** [comment]
@DongjaJ sure! give it a try!
