### ISSUE TITLE
Some links don't work.

### ISSUE THREAD

**Issue by rebase** [yorkie-team/yorkie-team.github.io#76]
**What happened**:
There are several links to redirect **/docs/server**. 

https://github.com/yorkie-team/yorkie-team.github.io/blob/508fa409f5ec5c8a4465ee77b5d55837427116d7/docs/index.mdx?plain=1#L20

https://github.com/yorkie-team/yorkie-team.github.io/blob/508fa409f5ec5c8a4465ee77b5d55837427116d7/docs/cli.mdx?plain=1#L121

https://github.com/yorkie-team/yorkie-team.github.io/blob/508fa409f5ec5c8a4465ee77b5d55837427116d7/pages/products.tsx#L252-L255

https://github.com/yorkie-team/yorkie-team.github.io/blob/508fa409f5ec5c8a4465ee77b5d55837427116d7/docs/self-hosted-server.mdx?plain=1#L90

https://github.com/yorkie-team/yorkie-team.github.io/blob/508fa409f5ec5c8a4465ee77b5d55837427116d7/components/Layout/MobileGnbDropdown.tsx#L121-L126

However, a file named 'server' does not exist under the docs folder. 
So Next.js shows 404.tsx.

The file must exist or refer to an available URL.

**What you expected to happen**:
working properly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Operating system:
- Browser and version:

**Comment by hackerwins** [comment]
@mihilt Thanks for your reporting.

I missed them in the previous PR.
https://github.com/yorkie-team/yorkie-team.github.io/pull/74
