### ISSUE TITLE
Add Quill example page to https://yorkie.dev/examples

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/yorkie-team.github.io#86]
**Description**:

Add Quill example to https://yorkie.dev/examples

We have a Quill example, but we haven't created a page on the homepage.
Let's create a page that displays the example.

- CodeMirror Page: https://github.com/yorkie-team/yorkie-team.github.io/blob/main/pages/examples/codemirror.tsx
- Quill Example in JS SDK: https://github.com/yorkie-team/yorkie-js-sdk/tree/main/examples/vanilla-quill

**Why**:

**Comment by g2hhh2ee** [comment]
Can I try this issue? 😊

**Comment by hackerwins** [comment]
@g2hhh2ee Sure. :) If you have any questions, please feel free to ask.

**Comment by g2hhh2ee** [comment]
@hackerwins 

Hi, 
I was working on this issue and realized that I don't have a thumbnail image file for the quill example. Is there an image file for the quill example?

![image](https://github.com/yorkie-team/yorkie-team.github.io/assets/57996351/7f938ff2-2977-4bbe-9e4b-7958e1fad02e)

**Comment by hackerwins** [comment]
We can capture thumbnail images from the site below.
- https://yorkie.dev/yorkie-js-sdk/examples/vanilla-quill/

**Comment by hackerwins** [comment]
This is fixed by https://github.com/yorkie-team/yorkie-team.github.io/pull/89
