### ISSUE TITLE
Add few more information at JS-SDK's documentation

### ISSUE THREAD

**Issue by banma1234** [yorkie-team/yorkie-team.github.io#95]
Description:

Add few more information at JS-SDK's documentation

Why:

Of course, we already have [JS SDK Reference](https://yorkie.dev/yorkie-js-sdk/api-reference/), still we need more information at JS-SDK document for new visitors. we need to pull several information of reference page up to the JS-SDK documentation.

**Comment by hackerwins** [comment]
I agree with this opinion. However, I will close this issue because it seems to be a duplicate issue with #98.
